Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.00                           0.00
  y                          -0.06                          -0.01
  z                          -0.00                          -0.00
abs                           0.06                           0.01
                    unit:  μC/cm2                 unit:  μC/cm2
