Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Sn          -1.30           -0.17 
      2      Sn          -1.30           -0.17 
      3      Te           1.61            0.21 
      4      Te           1.61            0.21 

Madelung Energy (eV)     -0.54           -0.01 
