Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                          -2.27                           0.25
  y                          -1.31                           0.14
  z                           1.90                          -0.21
abs                           3.24                           0.35
                    unit:  μC/cm2                 unit:  μC/cm2
