Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                           0.00                           0.00
  y                           0.00                           0.00
  z                           2.29                           0.74
abs                           2.29                           0.74
                    unit:  μC/cm2                 unit:  μC/cm2
