Polarization file from LOBSTER.
Units are  μC/cm2

         Rel. Mulliken pol. vector       Rel. Loewdin pol. vector
  x                          -3.25                          -1.41
  y                          -1.88                          -0.81
  z                          -0.00                          -0.00
abs                           3.75                           1.62
                    unit:  μC/cm2                 unit:  μC/cm2
